version: '3'
services:
  react_client:
    build:
      context: ./react_client
      dockerfile: ../base.node.Dockerfile
    volumes:
      - ./react_client/src:/app/src
    expose:
      - '3000'
    ports:
      - '3000:3000'
